name: XNIO and Remoting
'on':
  push:
    branches: ci-branch-1
env:
  MAVEN_OPTS: -Xms756M -Xmx1g
  OB_ISSUE_ID: 1
jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
    - run: echo hello!!
#    - uses: actions/checkout@v2
#      with:
#        ref: ci-branch-1
#    - uses: n1hility/cancel-previous-runs@v2
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
  xnio-build:
    name: xnio
    runs-on:
    - ubuntu-latest
    env:
      OB_ISSUE_DATA_JSON: .ci-tools/issue-data.json
    needs:
    - cancel-previous-runs
    outputs:
      version_xnio: ${{steps.pre-build.outputs.version}}
      git-sha: ${{steps.pre-build.outputs.git-sha}}
    steps:
    - uses: actions/checkout@v2
      with:
        repository: kabir/xnio
        ref: '3.8'
    - uses: actions/checkout@v2
      with:
        ref: ci-branch-1
        path: .ci-tools
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - id: pre-build
      uses: kabir/play-action/temp-pre-build@master
      with:
        build: 1
        custom: 0
    - name: Build with Maven
      run: 'mvn -B install -DskipTests '
    - name: Mount ~/.m2/repository to .m2-repo-mount since the actions can't access
        ~/.m2 directly
      run: mkdir .m2-repo-mount && sudo mount --rbind ~/.m2/repository/ .m2-repo-mount
    - uses: kabir/play-action/temp-post-build@master
      with:
        build: 1
        custom: 0
        component: xnio
    - name: Unmount .m2-repo-mount
      run: sudo umount .m2-repo-mount && rmdir .m2-repo-mount
    - name: Run multi-repo-ci-tool 'copy-logs' command
      if: ${{ failure() }}
      run: |
        java -jar .ci-tools/multi-repo-ci-tool.jar copy-logs . .project-build-logs/xnio
    - if: ${{ failure() }}
      run: |
        cd .project-build-logs
        zip -r xnio.zip xnio
        rm -rf xnio
    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: xnio_and_remoting-logs-20201120-121703
        path: .project-build-logs
  jboss-remoting-build:
    name: jboss-remoting
    runs-on:
    - ubuntu-latest
    env:
      OB_VERSION_XNIO: ${{ needs.xnio-build.outputs.version_xnio}}
      OB_ISSUE_DATA_JSON: .ci-tools/issue-data.json
    needs:
    - cancel-previous-runs
    - xnio-build
    outputs:
      version_jboss_remoting: ${{steps.pre-build.outputs.version}}
      git-sha: ${{steps.pre-build.outputs.git-sha}}
    steps:
    - uses: actions/checkout@v2
      with:
        repository: kabir/jboss-remoting
        ref: '5.0'
    - uses: actions/checkout@v2
      with:
        ref: ci-branch-1
        path: .ci-tools
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Mount ~/.m2/repository to .m2-repo-mount since the actions can't access
        ~/.m2 directly
      run: mkdir .m2-repo-mount && sudo mount --rbind ~/.m2/repository/ .m2-repo-mount
    - id: pre-build
      uses: kabir/play-action/temp-pre-build@master
      with:
        build: 1
        custom: 0
    - name: Build with Maven
      run: mvn -B install -DskipTests -Dxnio.version=${OB_VERSION_XNIO}
    - uses: kabir/play-action/temp-post-build@master
      with:
        build: 1
        custom: 0
        component: jboss-remoting
    - name: Unmount .m2-repo-mount
      run: sudo umount .m2-repo-mount && rmdir .m2-repo-mount
    - name: Run multi-repo-ci-tool 'copy-logs' command
      if: ${{ failure() }}
      run: |
        java -jar .ci-tools/multi-repo-ci-tool.jar copy-logs . .project-build-logs/jboss-remoting
    - if: ${{ failure() }}
      run: |
        cd .project-build-logs
        zip -r jboss-remoting.zip jboss-remoting
        rm -rf jboss-remoting
    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: xnio_and_remoting-logs-20201120-121703
        path: .project-build-logs
