name: Try Action
on:
  push:
env:
  MY_WORKFLOW_VAR: My Variable
jobs:
  sample-job:
    env:
     MY_NAME: Kabir
    name: Sample Job
    runs-on: [ubuntu-latest]
    steps:
     - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: 11
#       - run: |
#           which java
#       - uses: kabir/play-action@master
#         with:
#           name: "${MY_NAME}"
#           age: 49
#           town: London
     - uses: kabir/play-action/temp-generator@master
       with:
         name: "${MY_NAME}"
         age: 49
